services:
  rhel8:
    image: registry.access.redhat.com/ubi8/ubi-init:8.10
    container_name: rhel8
    hostname: ec2-hostname
    restart: unless-stopped
    privileged: true
    ports:
      - "2222:22"
    command: >
      bash -c "set -e;
      rpm -q openssh-server || { dnf install -y openssh-server; systemctl enable sshd; };
      sed -i -E 's/^#?PermitRootLogin .*/PermitRootLogin yes/; s/^#?PasswordAuthentication .*/PasswordAuthentication yes/' /etc/ssh/sshd_config;
      echo root:root | chpasswd;
      exec /sbin/init"